fix(ci): make dry-run publish failures visible
wasmCloud/wasmCloud pull request #1043
Opened 2023-11-20 15:32 UTC by connorsmith256

## Feature or Problem
We've had a couple instances where we fail to publish a crate, or after it's published, users cannot install it, because a downstream dependency had a breaking change. Since the dry-run step is not currently required to merge, it's okay to let it fail, and this should help make failures much more visible

2023-11-20 15:50 UTC, rvolosatovs requested changes
I am against this change - this will fail most of the time, because dry-publishing crates dependent on other (not published yet) crates within workspace may fail

2023-11-20 15:52 UTC, rvolosatovs commented
Note that this change would do nothing to prevent https://github.com/wasmCloud/wasmCloud/issues/1038

The CI on unrelated PRs could just suddenly start failing, which is not desired

2024-01-25 18:04 UTC, connorsmith256 commented
Reopening because this once again bit us. https://github.com/wasmCloud/wasmCloud/pull/1381 was able to be merged even though there was a compilation issue in the crate

2024-02-15 18:58 UTC, closed without merging

2024-02-15 19:00 UTC, brooksmtownsend commented
Just closing as we don't have a plan of action here unfortunately, not that we don't plan to do something like this. Looking into https://crates.io/crates/cargo-smart-release as well.