feat(*): Bumps our wasmcloud wit to 1.0
wasmCloud/wasmCloud pull request #1810
Opened 2024-04-03 21:29 UTC by thomastaylor312

This bumps our main `wasmcloud:bus` package and the package in the `runtime` crate to 1.0.0 in preparation for release. Also removes the use of the wasmcloud interface in tests where it wasn't needed

2024-04-03 21:29 UTC, thomastaylor312 commented
Please note that this is stacked on top of #1809 to avoid merge conflicts. I will rebase once the other is merged

2024-04-03 22:24 UTC, brooksmtownsend requested changes
Version bumps look great to me. Requesting changes since I think we should figure out these issues before we call the wits 1.0, but I don't think we have to hold this specific PR back as long as we're OK with it changing in `main`

2024-04-03 22:24 UTC, brooksmtownsend commented on wit/bus.wit
I see a pretty significant TODO in this WIT, do we want to make sure this interface is ready for stability?

What I think of as the (pseudocode) usage of this interface is:
```rust
wasi::keyvalue::set("foo", "bar"); // sets a key in whatever is linked on default
wasmcloud::bus::lattice::set_link_name("secret", "wasi:keyvalue/set");
wasi::keyvalue::set("foo", "p4ssw0rd"); // sets a key in whatever is linked on secret
```

If we removed the interfaces, then we could do the same as above with a little less code at the cost of setting the link name for every interface call, which makes me think the above is still necessary.

2024-04-03 22:24 UTC, brooksmtownsend commented on wit/bus.wit
A conversation for another PR is whether or not this implementation in the host works with different component instances (cc @vados-cosmonic, since we spoke about this)

2024-04-03 22:24 UTC, brooksmtownsend commented on wit/README.md
I think it would be great to include a small README here just noting that this WIT interface is used for the advanced use case of multiple links on the same interface (you could leave it at that.) Optional pointer to where the full list of WIT things we support (runtime?)

2024-04-03 22:32 UTC, thomastaylor312 commented on wit/README.md
I’d rather document it in the interface itself since docs can be generated from that

2024-04-03 22:33 UTC, thomastaylor312 commented on wit/bus.wit
We should actually figure that out here before we bump to 1.0

2024-04-04 20:43 UTC, thomastaylor312 commented on wit/bus.wit
So I think we should keep interfaces just so it can be more focused. If you have one interface that only uses a custom link name and the others are default, it would really suck to have to unset the link name with every call. I think we can make some nice wrappers for this that could go into `wasmcloud_actor` eventually

2024-04-04 20:49 UTC, thomastaylor312 commented on wit/README.md
Documentation added!

2024-04-04 20:49 UTC, thomastaylor312 commented
This will be ready to go once #1815 is merged. I'll rebase on that just to be sure before merging this

2024-04-05 16:10 UTC, brooksmtownsend approved these changes

2024-04-05 16:19 UTC, merged