chore/remove cluster issuers
wasmCloud/wasmCloud pull request #1828
Opened 2024-04-08 17:57 UTC by brooksmtownsend

- **chore(*)!: remove cluster_seed/cluster_issuers**
- **chore: update CONTRIBUTING.md**
- **chore(wasmcloud): bump to 1.0.0-rc.1**

## Feature or Problem
This PR removes the cluster_seed and cluster_issuers command line flags (and internal plumbing), and takes the chore to bump to wasmCloud 1.0.0-rc.1 when we're ready :rocket:

## Related Issues
See #1220 for the motivation behind cluster seed and cluster issuers being removed in favor of response signing verification.

## Release Information

## Consumer Impact
Because the `cluster_issuers` field in the HostData struct for providers is _not_ something that serde can deserialize if it's missing, we will pass an empty vec until we can ensure that we can release a new version of all of our capability providers that don't depend on this field being passed.

## Testing

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2024-04-08 21:27 UTC, ricochet approved these changes

2024-04-08 21:31 UTC, thomastaylor312 requested changes
One small docs change needs to happen but otherwise good

2024-04-08 21:31 UTC, thomastaylor312 commented on CONTRIBUTING.md
> +As a post-1.0 project, wasmCloud maintains a strong commitment to backward compatibility. All of our
😍

2024-04-08 21:31 UTC, thomastaylor312 commented on CONTRIBUTING.md
> +release(unless absolutely needed to fix a security issue). This often means that we have to tell people
What do we have to tell people?

2024-04-09 13:02 UTC, brooksmtownsend commented on CONTRIBUTING.md
> +release(unless absolutely needed to fix a security issue). This often means that we have to tell people
That the bird is the word

2024-04-09 15:38 UTC, thomastaylor312 approved these changes

2024-04-09 15:38 UTC, merged