feat: add echo messaging example
wasmCloud/wasmCloud pull request #1881
Opened 2024-04-11 21:28 UTC by brooksmtownsend

## Feature or Problem
This PR creates an example component called `echo-messaging` that will respond to any message received on the `wasmcloud:messaging` interface that includes a `reply_to` field with the same payload it received. The most basic example is exercised in the README, which is sending a `nats req` and receiving back the same payload.

## Related Issues
This will be great to test https://github.com/wasmCloud/wasmCloud/pull/1877

### Acceptance or Integration

### Manual Verification
I did make sure this worked

2024-04-12 02:03 UTC, thomastaylor312 requested changes
One small comment to address here

2024-04-12 02:03 UTC, thomastaylor312 commented on examples/rust/components/echo-messaging/Cargo.lock
Probably don't need the lock file committed for the example

2024-04-12 13:18 UTC, brooksmtownsend commented on examples/rust/components/echo-messaging/Cargo.lock
We have it committed for all other components so if we remove it from here I'd rather remove it from all

2024-04-13 15:30 UTC, thomastaylor312 approved these changes

2024-04-16 16:16 UTC, merged