feat(*): support provider config updates
wasmCloud/wasmCloud pull request #2436
Opened 2024-07-03 19:13 UTC by vados-cosmonic

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2024-07-23 20:48 UTC, brooksmtownsend requested changes
In general I think that this implements the functionality well, but I do have a bit of a concern here that now providers are connecting to JetStream directly whereas before they weren't. I think this might be going in the wrong direction when it comes to treating providers more like components, and may make a future WASI provider more difficult to implement.

What I envisioned for solving this issue was a similar method of updating, but using the `ConfigBundle` that's in the host that's specifically designed to watch the config bucket for changes in the specified keys, then publishing configuration updates to a handler the provider can implement to receive those updates. I don't think that would require too many changes to this PR, and it would solve the concern about cleaning up leftover keys in the CONFIGDATA bucket.

TL;DR, I think providers directly accessing JetStream isn't a pattern we should support, and we should keep the host as the only entity that can access that core piece of data for us.

What do you think @vados-cosmonic ? I can completely see the pros in terms of functionality of how it's implemented here, I just worry about what it means for the future of providers.

2024-07-24 14:41 UTC, vados-cosmonic commented
Hey @brooksmtownsend I definitely get those concerns! We currently have Providers doing a bit of connecting to NATS themselves (and there's nothing to stop them from doing so), so I'm not sure I quite see the difference (maybe Jetstream is a much more fundamental functionality than regular NATS connections?) *but* I definitely think that we could formalize it a different way. 

I *think* that in the future WASI providers will either:

1. Get limited access to sockets
2. Have to use an explicit interface that is filled in/triggered by the host upon updates/etc

In both cases, the changes to `provider-sdk` to move from reading Jetstream directly to either allowing access to jetstream (i.e. the provider is still doing the network access), to doing the listening *on behalf of* the WASI provider isn't too disrupted by this current implementation. That said, I do see your concern!

I think the problem here is that we've done our best to sort of... skip formalizing a host <-> provider communication mechanism, we've left it to NATS (which we've benefitted from)...

What do you think would be a good communication process between hosts and providers that could work for this use case? I was avoiding regular NATS listen/send because chunking may be required, and we don't really have any other mechanisms AFAICT.

2024-07-29 17:51 UTC, thomastaylor312 commented
Hey @vados-cosmonic I think I get where you're coming from, but I also think some context might be helpful here along with some commentary on some of the reasoning. So @brooksmtownsend brought up `ConfigBundle` because I explicitly designed the `bundle.changed().await` method to enable the host to watch for config changes and then send it over a new NATS topic to a provider. This matches how we deliver everything else to a provider so we are following the same pattern. With that in mind, a couple of notes:

> I think the problem here is that we've done our best to sort of... skip formalizing a host <-> provider communication mechanism, we've left it to NATS (which we've benefitted from)...

The formalization has been the provider SDK, which by rule has used a NATS topic API. However, this goes back to the same rationale about why we removed putting links directly into the bucket from the ctl interface and changed it back to a topic. Acknowledging that, yes, NATS KV is just a stream of messages under the hood, you would never have something that uses an API elsewhere connect directly to a database and receive values from it. Case in point of this: if something besides the host was relying on reading link definitions from the KV store, that is now making your database an API. We're going to have to change how those are structured soon because they cause a race condition. If something was relying on those structures, then they would now be broken. This would greatly expand the work needed for backwards compatibility with the host. 

> What do you think would be a good communication process between hosts and providers that could work for this use case?

The last point leads me to the answer to this question: It should be over NATS as part of the "API contract" (which as you noted, we could probably formalize better) that let's a provider listen for incoming config updates that it can then do something with. I think this is a much cleaner API for two reasons: First is that where the data is coming from and how it is shaped in storage is decoupled from what the API looks like. Second, if we have a bug in how things are being transmitted (or changes in storage) we don't have to recompile all providers with a new SDK version. The host can change it and since it is an API, the SDK just goes on consuming it.

> I was avoiding regular NATS listen/send because chunking may be required, and we don't really have any other mechanisms AFAICT.

This was an interesting point I hadn't thought of before, but I don't think it is a problem right now. This would mean that your config is over 1MB. We probably should be setting a max size on the config bucket when we set it up (likely 1MB), so we should open an issue for that. However, I don't think this is a problem in the short term

2024-07-30 02:09 UTC, vados-cosmonic commented
Thanks @thomastaylor312 for the deeper explanation -- I think I see what ya'll were expecting the solution to look like with the current API conventions.

As far as the other stuff, that all sounds reasonable -- I'll refactor this PR to use a new NATS topic.

> This was an interesting point I hadn't thought of before, but I don't think it is a problem right now. This would mean that your config is over 1MB. We probably should be setting a max size on the config bucket when we set it up (likely 1MB), so we should open an issue for that. However, I don't think this is a problem in the short term

Well this certainly solves my reason to use KV directly -- will do this, and we can cross that bridge when someone tries to send too much config data.

2024-08-06 14:43 UTC, vados-cosmonic commented on crates/host/src/wasmbus/mod.rs
> +/// A (usually running) Provider instance
Yeah the provider could actually exit -- just having one of these doesn't necessary mean that a provider is running... For example we don't hold the actual `Child`... I'll update the comment but one thing that I noticed is that we actually just let the `Child` object drop

2024-08-06 14:43 UTC, vados-cosmonic commented on crates/host/src/wasmbus/config.rs
> +        let mut bundle = ConfigBundle(vec![
No it's not! the `::new` should be there!

2024-08-06 14:45 UTC, vados-cosmonic commented on crates/host/src/wasmbus/mod.rs
> +        config_update_task.abort();
So we didn't do that up until now, but I'd suggest addressing this in a follow up -- we actually *don't save* the `Child` task of the provider so we can try to do anything with it... We just :crossed_fingers: that the shutdown is processed correctly (which means the provider should shut itself down)...

2024-08-06 14:50 UTC, vados-cosmonic commented on crates/host/src/wasmbus/mod.rs
> +/// A (usually running) Provider instance
Updated the comment here!

2024-08-06 14:50 UTC, vados-cosmonic commented on crates/host/src/wasmbus/mod.rs
> +        config_update_task.abort();
Created an issue for this:

https://github.com/wasmCloud/wasmCloud/issues/2698

2024-08-09 16:32 UTC, brooksmtownsend approved these changes
Great stuff @vados-cosmonic !

2024-08-09 16:49 UTC, merged