WIP feat(washboard-ui): indicate if asset is managed by wamd
wasmCloud/wasmCloud pull request #2447
Opened 2024-07-08 08:52 UTC by markkovari

## Feature or Problem

Some of the resources are managed by wadm and it is not easy to know which one is manually created and which one is by wadm.
Obviously the feature flag part is part of the WIP only.

## Related Issues

#844 
asset annotation for wadm assets

## Release Information

## Consumer Impact

## Testing

Testing might be interesting and I am waiting for your opinion as well.

Steps:
1. ```bash cd washboard-ui```
2. ```make run-ui```
3. Start multiple assets with wadm and without wadm.
4. Switch between the features and reload.

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2024-07-15 13:26 UTC, markkovari commented
Hey @brooksmtownsend, sorry for the ping and the delay. I know that this PR is failing. (since I created multiple options and did not bother to cleanup until we pick one). If you would look at this would be great, although this is kinda a cosmetic thing only.

Appreciate.

2024-07-15 14:52 UTC, brooksmtownsend commented
Thank you for the poke @markkovari ! I left a comment on the issue itself with a tag for Lachlan who made the washboard to see if he has any opinions 😄

2024-07-16 12:59 UTC, lachieh requested changes
A few small changes, but looks good to me! Thanks for the contribution, @markkovari!

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/wadm-indicator/wadm-managed-toggle.tsx
> +        <SelectValue placeholder="Select how the wadm managed assets should be differentiated" />
```suggestion
        <SelectValue placeholder="How to show managed indicator" />
```

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/wadm-indicator/wadm-indicator.tsx
> +const featureMapper: Map<WadmManagedAssetOption, [ColumValue, ColumValue]> = new Map([
```suggestion
type ColumnValue = ReactElement | string | null;

const featureMapper: Map<WadmManagedAssetOption, [ColumnValue, ColumnValue]> = new Map([
```

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/wadm-indicator/wadm-indicator.tsx
> +export function MadmManagedIndicator(annotations: Record<string, string>): ColumValue {
```suggestion
export function WadmManagedIndicator(annotations: Record<string, string>): ColumnValue {
```

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/components-table.tsx
> +import {MadmManagedIndicator} from './wadm-indicator/wadm-indicator';
```suggestion
import {WadmManagedIndicator} from './wadm-indicator/wadm-indicator';
```

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/components-table.tsx
> +    cell: (info) => MadmManagedIndicator(info.getValue()),
```suggestion
    cell: (info) => WadmManagedIndicator(info.getValue()),
```

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/providers-table.tsx
> +import {MadmManagedIndicator} from './wadm-indicator/wadm-indicator';
```suggestion
import {WadmManagedIndicator} from './wadm-indicator/wadm-indicator';
```

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/providers-table.tsx
> +    cell: (info) => MadmManagedIndicator(info.getValue()),
```suggestion
    cell: (info) => WadmManagedIndicator(info.getValue()),
```

2024-07-16 12:59 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/contexts/settings-context.tsx
> +  );
```suggestion
export const SettingsContext = createContext<SettingsContextValue>({
  darkMode: DarkModeOption.System,
  setDarkMode: () => null,
  wadmManagedAsset: WadmManagedAssetOption.Logo,
  setWadmManagedAsset: () => null,
});

export function SettingsProvider({children}: PropsWithChildren): ReactElement {
  const [darkMode, setDarkMode] = useLocalStorage('theme', DarkModeOption.System);

  const [wadmManagedAsset, setWadmManagedAsset] = useLocalStorage(
    'wadmManagedAsset',
    WadmManagedAssetOption.Logo,
  );
```

Let's go with the logo as default! 💥

2024-07-16 13:06 UTC, lachieh commented on washboard-ui/packages/washboard-ui/src/app/components/wadm-indicator/wadm-indicator.tsx
> +const featureMapper: Map<WadmManagedAssetOption, [ColumValue, ColumValue]> = new Map([
You could also use `React.ReactNode` here unless you prefer the specificity.

2024-07-16 14:25 UTC, markkovari commented on washboard-ui/packages/washboard-ui/src/app/components/components-table.tsx
Wow, this is so much better. One fun fact that I did not read about and was hard to figure out. All of the columns needs to have an id otherwise does not really work.

And I moved the Logo to the first place too.
Thanks

2024-07-16 14:27 UTC, lachieh approved these changes
Love it!

2024-07-16 14:29 UTC, lachieh commented
Closes #844

2024-07-16 16:43 UTC, merged