chore(ci): remove wit-bindgen-cli from test runs
wasmCloud/wasmCloud pull request #3441
Opened 2024-10-24 18:29 UTC by vados-cosmonic

This commit removes `wit-bindgen-cli` from tests, which was required when building golang tooling. Since upstream deps have changed (it no longer tries to call `wit-bindgen` but instead calls `wasm-tools`, we should be OK removing `wit-bindgen-cli`.

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2024-10-28 18:58 UTC, brooksmtownsend requested changes

2024-10-28 18:58 UTC, brooksmtownsend commented on examples/golang/providers/custom-template/component/customtemplate.go
> +// }
This should probably all be commented back in right?

2024-10-29 03:02 UTC, vados-cosmonic commented
Sorry this wasn't clear but this was a WIP, I should have marked it so -- https://github.com/wasmCloud/wasmCloud/pull/3441/commits/0d9dcff54ee31ac62fcef4700fd7cc15923ee100

What I found out ~4 days ago was that this code doesn't actually work, especially if you don't have the tooling installed, because `go run` won't actually download and install the thing automatically, you need the "tools.go" pattern for that, which is a wider change, and there's a PR that does [that and other stuff](https://github.com/wasmCloud/wasmCloud/pull/3132) which actually should be broken down and used instead (excluding the "tools.go" adoption change, IIRC). 

Closing this for now, as other PRs have started landing to update the Go examples as well!

2024-10-29 03:02 UTC, closed without merging

2024-10-29 03:17 UTC, joonas commented
it's worth noting that with the changes that are going in to [component-sdk-go](https://github.com/wasmcloud/component-sdk-go), I think fast approaching state where we will no longer need the `tools.go` trick.