feat(wash-cli): enable purging all links
wasmCloud/wasmCloud pull request #3698
Opened 2024-11-26 14:30 UTC by vados-cosmonic

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2024-12-31 14:46 UTC, brooksmtownsend requested changes
Only request is to have the test run the command and make sure all the links get deleted 😄

2024-12-31 14:46 UTC, brooksmtownsend commented on crates/wash-cli/src/cmd/link/del.rs
> +                "Are you sure you want to iteratively delete all links in the cluster? (this action cannot be reversed)",
```suggestion
                "Are you sure you want to delete all links in the cluster? (this action cannot be reversed)",
```

supernit

2024-12-31 14:46 UTC, brooksmtownsend commented on crates/wash-cli/tests/wash_link.rs
> +async fn integration_link_del_all_serial() -> Result<()> {
I think it would be good for this test to define a few different links and then ensure that the delete all deletes all of them

2025-01-06 16:20 UTC, vados-cosmonic commented on crates/wash-cli/tests/wash_link.rs
> +async fn integration_link_del_all_serial() -> Result<()> {
Ah thanks, definitely forgot to actually fill out this test!

2025-01-06 23:19 UTC, thomastaylor312 approved these changes
One super minor doc comment change needed. Approving so you can change and resolve the comment!

2025-01-06 23:19 UTC, thomastaylor312 commented on crates/wash-cli/src/cmd/link/query.rs
> +//! Functionality enabling the `wash link del` subcommand
This should read `wash link get`

2025-01-07 07:01 UTC, vados-cosmonic commented on crates/wash-cli/src/cmd/link/query.rs
> +//! Functionality enabling the `wash link del` subcommand
Ah great catch, just fixed this!

2025-01-07 08:07 UTC, merged