fix(logs): allow debug and trace logs in release mode
wasmCloud/wasmCloud pull request #466
Opened 2023-08-13 19:09 UTC by connorsmith256

## Feature or Problem
This removes a feature from the tracing crate, allowing higher log verbosity than info for release builds

Allowing users to specify debug/trace-level logs is important for debugging release builds. The size of the debug build is prohibitively large in some environments where viewing debug/trace logs is still helpful

2023-08-13 19:34 UTC, rvolosatovs requested changes
I am against this change, since I consider this a security vulnerability. This would cause potentially sensitive user data to be leaked unprotected in any way, which is unacceptable for a system that calls itself "secure".

Why not deploy a development profile build to a staging/development environment? Debugging does not belong in production.

2023-08-14 19:00 UTC, rvolosatovs commented
As discussed offline, I'm fine with allowing debug (preferable) or even trace level logs, as done here (last resort) in release builds as long as there's a clear TODO stating that this should be revisited (because at present trace every single Wasm call with full payloads cleartext are printed to trace) and an issue filed.

The issue should have "technical debt" and "security" labels (or appropriate alternatives) associated with it and have a link to this PR and discussion.

@connorsmith256

2023-08-14 19:08 UTC, connorsmith256 commented
@rvolosatovs Issue captured in https://github.com/wasmCloud/wasmCloud/issues/468

2023-08-14 19:10 UTC, rvolosatovs approved these changes

2023-08-14 19:23 UTC, merged