Pre-vacation safety WIP checkin. This does not yet build
wasmCloud/wasmCloud pull request #49
Opened 2020-12-18 22:06 UTC by autodidaddict

Not yet ready for full review. Starting the PR as a WIP before vacation.

2021-01-07 17:42 UTC, autodidaddict commented
@brooksmtownsend when you go through this PR, can you please ensure that this branch doesn't break any of your REPL demo activities?

2021-01-07 18:22 UTC, brooksmtownsend commented
@autodidaddict Sure thing. Is it ready for review now? I'd be happy to run through the REPL demo too before it's ready if you'd like.

2021-01-07 18:56 UTC, autodidaddict commented
It's ready for testing via the REPL, yes. Not sure if I'm ready with the code being complete.

2021-01-07 20:08 UTC, brooksmtownsend commented
KVCounter example works great with this branch (latest commit #8bb6bc8). I appreciate the link name for the lattice cache, could we do that with extras too? (Here's the host inventory)
```
                       Host Inventory (NCA3W27HJLGSY62V5XKJXZTVMBWMXRAOC2BEWPYK3JUIIH45YGLL4KU4)

 hostcore.os                                                macos
 hostcore.arch                                              x86_64
 hostcore.osfamily                                          unix

 Actor ID                                                   Image Reference
 MC6Z57M3HOUPIAMTZDMKFBJ5AZ3UOWZ4WJYO7DZNA6567XSJNBUQP55I   wascc.azurecr.io/kvcounter:v0.1.1

 Provider ID                                                Link Name                  Image Reference
 VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M   default                    wascc.azurecr.io/httpsrv:v0.9.2
 VAHNM37G4ARHZ3CYHB3L34M6TYQWQR6IZ4QVYC4NYZWTJCJ2LWP7S6Z2   __wasmcloud_lattice_cache  N/A
 VAZVC4RX54J2NVCMCW7BPCAHGGG5XZXDBXFUMDUXGESTMQEJLC3YVZWB   default                    wascc.azurecr.io/redis:v0.9.2
 VDHPKGFKDI34Y4RN4PWWZHRYZ6373HYRSNNEM4UTDLLOGO5B37TSVREP   default                    N/A
```

2021-01-07 20:11 UTC, autodidaddict commented
This looks fantastic. We can't use a "hidden" link name for extras because that's something that actors use via the interface (we haven't generated it yet...). In other words, regular actors that want GUIDs or random numbers need to make calls to "wascc:extras" "default".

2021-01-07 20:13 UTC, brooksmtownsend commented
Ah okay. I forgot about https://github.com/wasmCloud/wasmCloud/issues/24 actually, which would directly address my concern with someone looking at this random provider and saying "huh, don't recognize that, let's just stop it"

2021-01-07 20:51 UTC, autodidaddict commented
Also worth testing - fire up a `wasmCloud` binary in a shell with the `KVCACHE_NATS_URL` environment variable set.
Then do a `wash up` in another shell, also with `KVCACHE_NATS_URL` set. 
Then make sure that all of the "multiplayer" repl commands work properly, assuring that the kv cache replication is working.

I've tested this locally a bit, but not thoroughly since I've been trying to automate some of the other distributed tests (to no avail)

2021-01-08 20:13 UTC, brooksmtownsend requested changes
A couple places for changes, submitting this before I've run the tests locally as I need to reboot. One more suggestion is that I saw many warnings during compilation, we should consider opening an issue to address cargo / clippy warnings before the 0.15.0 release to clean up the code.

2021-01-08 20:13 UTC, brooksmtownsend commented on crates/wasmcloud-host/src/messagebus/latticecache_client.rs
> +    pub async fn get_oci_references(&self) -> Result<Vec<String>> {
Does this comment mean to say that I can iterate through this list to retrieve all of the image reference mappings?

2021-01-08 20:20 UTC, autodidaddict commented on crates/wasmcloud-host/src/host_controller/hc_actor.rs
> +                new_actor.send(init).await??;
they can bubble up. the first `?` catches the "mailbox error" from actix, the second unwraps the Result that was returned by the actor.

2021-01-08 20:21 UTC, autodidaddict commented on crates/wasmcloud-host/src/messagebus/utils.rs
> +        "ACOJJN6WUP4ODD75XEBKKTCCUJJCY5ZKQ56XVKYK4BEJWGVAOOQHZMCW".to_string(),
Yep that's why we can also embed the JWTs for the extras and default kvcache providers.

2021-01-11 15:07 UTC, brooksmtownsend approved these changes

2021-01-12 15:01 UTC, merged