chore: move washboard to its own directory
wasmCloud/wasmCloud pull request #764
Opened 2023-10-19 03:40 UTC by connorsmith256

## Feature or Problem
This is the minimal amount of work to split the `washboard` directory out of `wash` into its own top-level directory

The washboard doesn't have any CI yet

@lachieh should I commit changes to `dist/`?

## Testing

### Manual Verification
- built the washboard: `cd washboard && make build-ui && cd -`
- built wash: `cd wash && cargo build`
- ran wash: `./target/debug/wash up --nats-websocket-port 4001`
- ran the washboard: `./target/debug/wash ui --experimental`

2023-10-19 03:41 UTC, lachieh commented
Yes please, until we have a release process

2023-10-19 07:45 UTC, rvolosatovs approved these changes

2023-10-19 16:08 UTC, connorsmith256 commented
On second thought, I'll leave this in draft until we've archived the wash repo. I don't want to make it more difficult to cherry-pick changes from there

2023-10-31 00:53 UTC, lachieh requested changes

2023-10-31 00:53 UTC, lachieh commented on washboard-ui/Makefile
> +	@$(NPM) instal
I think you dropped this `l`

2023-10-31 06:45 UTC, rvolosatovs approved these changes
I'm very surprised that using the relative path to parent directory for the washboard worked here

2023-10-31 16:01 UTC, connorsmith256 commented on washboard-ui/Makefile
> +	@$(NPM) instal
Oops! Nice catch 🙏

2023-10-31 16:43 UTC, lachieh approved these changes

2023-10-31 17:01 UTC, brooksmtownsend approved these changes

2023-10-31 17:01 UTC, merged

2023-10-31 17:43 UTC, rvolosatovs commented
Looks like you forgot to update the `paths` triggers for wash CI, which builds UI