ci: publish latest tag
wasmCloud/wasmCloud pull request #765
Opened 2023-10-19 20:15 UTC by connorsmith256

## Feature or Problem
I had a sad:
```
docker run wasmcloud/wasmcloud:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
wasmcloud 0.18.2
```

2023-10-19 20:16 UTC, connorsmith256 commented
I'm not sure how `buildah` works, so correct me if this is not the right approach 🙂

2023-10-19 21:52 UTC, rvolosatovs requested changes
Originally, I did not add this until we were still working on stabilizing the Rust host.
Approach LGTM, but we need to make sure to only publish `latest` on non-RC versions, so I am afraid we will have to add a `if`-gated step which would check for a non-RC tag to publish latest

2023-10-19 22:41 UTC, connorsmith256 commented
Thanks @rvolosatovs, I hadn't considered publishing over `latest` on `rc` tags 👍

2023-10-20 10:29 UTC, rvolosatovs approved these changes

2023-10-20 15:24 UTC, merged