Solve #757 [DRAFT]
wasmCloud/wasmCloud pull request #783
Opened 2023-10-23 14:48 UTC by professorabhay

Make the required changes as per need in #757

2023-10-23 17:27 UTC, thomastaylor312 requested changes
Great start here! There are a few changes needed around ordering. Let me know if you need any more clarification on Rust things!

2023-10-23 17:27 UTC, thomastaylor312 commented on src/main.rs
> +    let mut labels = HashMap::from([
So when you declare this variable, you are actually overriding the `labels` value declared on 339. The other thing is that these are the default labels so they should be the ones you start from and then `extend` them with the other user provided data. Generally the order of precedence in most projects is:

1. Command line flags
2. Env vars
3. Defaults

So what you'll probably want to do is start with:

```rust
let mut labels = HashMap::from([
    ("hostcore.arch".into(), ARCH.into()),
    ("hostcore.os".into(), OS.into()),
    ("hostcore.osfamily".into(), FAMILY.into()),
]);
```

Then `.extend` it with the stuff from 339-345

2023-10-23 17:27 UTC, thomastaylor312 commented on src/main.rs
> +        labels.extend(config.labels.clone().into_iter());
This line is no longer needed because it is coming from `args` above

2023-10-24 09:12 UTC, professorabhay commented
hey @thomastaylor312, Kindly take a look now !

2023-10-24 19:58 UTC, thomastaylor312 requested changes
The code itself is looking correct, but you're missing some imports and updates to where the labels are being used!

2023-10-24 19:58 UTC, thomastaylor312 commented on crates/host/src/wasmbus/mod.rs
> -        let mut labels = HashMap::from([
You'll need to make sure you update places that were using `labels` to use `config.labels` instead in this function. You'll also need to remove some old imports you no longer need. If you run `cargo check --workspace`, you should see all of the compile errors and the warnings of imports you should remove

2023-10-24 19:58 UTC, thomastaylor312 commented on src/main.rs
> +        ("hostcore.arch".into(), ARCH.into()),
You'll probably need to add this imports here. Once again, `cargo check` is your friend!

2023-10-27 21:44 UTC, thomastaylor312 commented
Hey @professorabhay, just circling back to see if you needed any help

2023-11-14 01:20 UTC, closed without merging

2023-11-14 01:20 UTC, thomastaylor312 commented
Since it has been a bit since we’ve heard anything, I’m going to go ahead and close for now. Few free to reopen if you have more time!